const bancoPerguntas = [
    // --- FRONT-END JÚNIOR ---
    { q: "O que é o DOM?", a: "Árvore de objetos do HTML.", cat: "frontend", nivel: "junior" },
    { q: "Diferença entre let, const e var?", a: "var tem escopo de função; let/const de bloco.", cat: "frontend", nivel: "junior" },
    { q: "O que é CSS Flexbox?", a: "Modelo de layout para distribuir espaço entre itens.", cat: "frontend", nivel: "junior" },
    { q: "O que é um elemento semântico?", a: "Tags com significado próprio (ex: <header>, <footer>).", cat: "frontend", nivel: "junior" },
    { q: "Como centralizar uma div?", a: "Display flex, justify-content e align-items center.", cat: "frontend", nivel: "junior" },
    { q: "O que é o seletor universal (*)?", a: "Seleciona todos os elementos do documento.", cat: "frontend", nivel: "junior" },
    { q: "O que é um evento em JS?", a: "Ações disparadas pelo usuário ou navegador.", cat: "frontend", nivel: "junior" },
    { q: "Para que serve o localStorage?", a: "Armazenar dados localmente no navegador de forma persistente.", cat: "frontend", nivel: "junior" },
    { q: "O que é o z-index?", a: "Controla a ordem de empilhamento de elementos.", cat: "frontend", nivel: "junior" },
    { q: "O que é um Array?", a: "Estrutura para armazenar múltiplos valores em uma variável.", cat: "frontend", nivel: "junior" },
    { q: "O que é uma Arrow Function?", a: "Sintaxe curta para criar funções em JS.", cat: "frontend", nivel: "junior" },
    { q: "O que é o overflow?", a: "Define o que acontece se o conteúdo passar do limite do box.", cat: "frontend", nivel: "junior" },
    { q: "O que é o Box Model?", a: "Margem, borda, padding e conteúdo.", cat: "frontend", nivel: "junior" },
    { q: "Qual a diferença de == e ===?", a: "== ignora tipo, === checa valor e tipo.", cat: "frontend", nivel: "junior" },
    { q: "O que é responsividade?", a: "Adaptação da tela em diferentes dispositivos.", cat: "frontend", nivel: "junior" },
    { q: "O que faz o comando npm init?", a: "Cria um package.json no projeto.", cat: "frontend", nivel: "junior" },
    { q: "Para que serve o 'alt' na imagem?", a: "Acessibilidade e SEO.", cat: "frontend", nivel: "junior" },
    { q: "O que é um callback?", a: "Função passada como argumento para outra função.", cat: "frontend", nivel: "junior" },
    { q: "Como declarar uma variável constante?", a: "Usando a palavra-chave const.", cat: "frontend", nivel: "junior" },
    { q: "O que é o método map()?", a: "Cria um novo array com resultados da chamada de função.", cat: "frontend", nivel: "junior" },
    { q: "O que é um formulário no HTML?", a: "Tag para coletar inputs do usuário.", cat: "frontend", nivel: "junior" },
    { q: "Diferença de id e class?", a: "ID é único, class pode repetir.", cat: "frontend", nivel: "junior" },
    { q: "O que é um link absoluto?", a: "URL completa com domínio.", cat: "frontend", nivel: "junior" },
    { q: "O que é a tag script?", a: "Define código JS na página.", cat: "frontend", nivel: "junior" },
    { q: "O que é um hover no CSS?", a: "Pseudo-classe aplicada ao passar o mouse.", cat: "frontend", nivel: "junior" },
    { q: "Como comentar em CSS?", a: "/* comentário */.", cat: "frontend", nivel: "junior" },
    { q: "O que é o console.log?", a: "Comando para debugar no console.", cat: "frontend", nivel: "junior" },
    { q: "O que é padding?", a: "Espaço interno entre conteúdo e borda.", cat: "frontend", nivel: "junior" },
    { q: "O que é margin?", a: "Espaço externo em volta da borda.", cat: "frontend", nivel: "junior" },
    { q: "O que é um selector de tag?", a: "Seleciona todos elementos daquela tag (ex: h1).", cat: "frontend", nivel: "junior" },

    // --- FRONT-END PLENO ---
    { q: "O que é o Virtual DOM?", a: "Cópia leve para otimizar renderizações.", cat: "frontend", nivel: "pleno" },
    { q: "Para que serve o useEffect?", a: "Gerenciar efeitos colaterais (API, subscrições).", cat: "frontend", nivel: "pleno" },
    { q: "O que é State no React?", a: "Dados que controlam a renderização do componente.", cat: "frontend", nivel: "pleno" },
    { q: "O que é um HOC (Higher Order Component)?", a: "Função que recebe um componente e retorna outro.", cat: "frontend", nivel: "pleno" },
    { q: "Como funciona o Event Loop?", a: "Gerencia a fila de tarefas assíncronas.", cat: "frontend", nivel: "pleno" },
    { q: "O que é Closures?", a: "Função que lembra seu escopo léxico.", cat: "frontend", nivel: "pleno" },
    { q: "O que é memoization?", a: "Guardar resultados de funções caras.", cat: "frontend", nivel: "pleno" },
    { q: "Diferença entre reflow e repaint?", a: "Reflow muda geometria, Repaint muda estilo visual.", cat: "frontend", nivel: "pleno" },
    { q: "O que é um Promise?", a: "Objeto que representa conclusão de operação assíncrona.", cat: "frontend", nivel: "pleno" },
    { q: "O que é o Context API?", a: "API para compartilhar estados entre componentes sem prop drilling.", cat: "frontend", nivel: "pleno" },
    { q: "O que é lazy loading?", a: "Carregar recursos apenas quando necessários.", cat: "frontend", nivel: "pleno" },
    { q: "O que são web workers?", a: "Scripts rodando em background fora da thread principal.", cat: "frontend", nivel: "pleno" },
    { q: "O que é o spread operator (...)?", a: "Expande elementos de um iterável.", cat: "frontend", nivel: "pleno" },
    { q: "O que é destructuring?", a: "Extrair propriedades de objetos ou arrays.", cat: "frontend", nivel: "pleno" },
    { q: "O que é SEO técnico?", a: "Otimizações de infraestrutura para buscadores.", cat: "frontend", nivel: "pleno" },
    { q: "Como evitar XSS?", a: "Sanitizando inputs e escapando saídas.", cat: "frontend", nivel: "pleno" },
    { q: "O que é CORS?", a: "Política que restringe recursos entre domínios.", cat: "frontend", nivel: "pleno" },
    { q: "Diferença de sessionStorage e localStorage?", a: "Session dura enquanto a aba estiver aberta.", cat: "frontend", nivel: "pleno" },
    { q: "O que é uma SPA?", a: "Aplicação de página única sem reload.", cat: "frontend", nivel: "pleno" },
    { q: "O que é um Web Component?", a: "Custom elements reutilizáveis nativos.", cat: "frontend", nivel: "pleno" },
    { q: "O que é PWA?", a: "Progressive Web App com cara de nativo.", cat: "frontend", nivel: "pleno" },
    { q: "O que é o Redux?", a: "Contêiner de estado previsível.", cat: "frontend", nivel: "pleno" },
    { q: "O que é CSS Modules?", a: "CSS com escopo local.", cat: "frontend", nivel: "pleno" },
    { q: "O que é um test e2e?", a: "Teste que simula jornada do usuário.", cat: "frontend", nivel: "pleno" },
    { q: "O que é TypeScript?", a: "Superset do JS com tipagem estática.", cat: "frontend", nivel: "pleno" },
    { q: "O que é um Interface no TS?", a: "Define a estrutura de um objeto.", cat: "frontend", nivel: "pleno" },
    { q: "O que é debounce?", a: "Atrasar execução de função repetitiva.", cat: "frontend", nivel: "pleno" },
    { q: "O que é throttle?", a: "Limitar execução de função por tempo.", cat: "frontend", nivel: "pleno" },
    { q: "O que é strict mode?", a: "Modo que força erros em práticas ruins de JS.", cat: "frontend", nivel: "pleno" },
    { q: "O que é shadow DOM?", a: "DOM encapsulado e isolado do principal.", cat: "frontend", nivel: "pleno" },

    // --- BACK-END JÚNIOR ---
    { q: "O que é API REST?", a: "Arquitetura baseada em recursos.", cat: "backend", nivel: "junior" },
    { q: "O que faz um servidor?", a: "Atende requisições de clientes.", cat: "backend", nivel: "junior" },
    { q: "Diferença entre GET e POST?", a: "GET busca, POST envia.", cat: "backend", nivel: "junior" },
    { q: "O que é SQL?", a: "Linguagem para banco de dados relacional.", cat: "backend", nivel: "junior" },
    { q: "O que é uma primary key?", a: "Identificador único de linha.", cat: "backend", nivel: "junior" },
    { q: "O que é JSON?", a: "Formato de dados leve.", cat: "backend", nivel: "junior" },
    { q: "O que é HTTP 404?", a: "Erro de recurso não encontrado.", cat: "backend", nivel: "junior" },
    { q: "O que é HTTP 500?", a: "Erro interno do servidor.", cat: "backend", nivel: "junior" },
    { q: "O que é um banco NoSQL?", a: "Banco sem tabelas rígidas.", cat: "backend", nivel: "junior" },
    { q: "O que é o Node.js?", a: "Runtime de JS para servidores.", cat: "backend", nivel: "junior" },
    { q: "O que é um endpoint?", a: "URL que acessa uma funcionalidade.", cat: "backend", nivel: "junior" },
    { q: "O que é Git?", a: "Sistema de controle de versão.", cat: "backend", nivel: "junior" },
    { q: "O que é um commit?", a: "Registro de mudanças no git.", cat: "backend", nivel: "junior" },
    { q: "O que é Docker?", a: "Containerização de aplicações.", cat: "backend", nivel: "junior" },
    { q: "O que é env vars?", a: "Variáveis de ambiente confidenciais.", cat: "backend", nivel: "junior" },
    { q: "Diferença de 200 e 201?", a: "200 sucesso, 201 criado.", cat: "backend", nivel: "junior" },
    { q: "O que é um log?", a: "Registro de eventos da aplicação.", cat: "backend", nivel: "junior" },
    { q: "O que é SSH?", a: "Protocolo para acesso remoto seguro.", cat: "backend", nivel: "junior" },
    { q: "O que é CRUD?", a: "Create, Read, Update, Delete.", cat: "backend", nivel: "junior" },
    { q: "O que é o npm?", a: "Gerenciador de pacotes JS.", cat: "backend", nivel: "junior" },
    { q: "O que é uma porta?", a: "Endpoint lógico de comunicação.", cat: "backend", nivel: "junior" },
    { q: "O que é o body em um POST?", a: "Corpo com os dados enviados.", cat: "backend", nivel: "junior" },
    { q: "O que é uma query string?", a: "Parâmetros enviados na URL.", cat: "backend", nivel: "junior" },
    { q: "O que é HTTPS?", a: "HTTP com criptografia SSL.", cat: "backend", nivel: "junior" },
    { q: "O que é um banco de dados?", a: "Local de armazenamento persistente.", cat: "backend", nivel: "junior" },
    { q: "O que é autenticação?", a: "Verificar a identidade.", cat: "backend", nivel: "junior" },
    { q: "O que é autorização?", a: "Verificar o nível de acesso.", cat: "backend", nivel: "junior" },
    { q: "O que é uma função assíncrona?", a: "Função que roda sem bloquear o fluxo.", cat: "backend", nivel: "junior" },
    { q: "O que é o console?", a: "Interface CLI de depuração.", cat: "backend", nivel: "junior" },
    { q: "O que é o README?", a: "Documentação inicial do projeto.", cat: "backend", nivel: "junior" },

    // --- BACK-END PLENO ---
    { q: "O que é JWT?", a: "Token para autenticação Stateless.", cat: "backend", nivel: "pleno" },
    { q: "O que é Middleware?", a: "Intermediário entre requisição e resposta.", cat: "backend", nivel: "pleno" },
    { q: "O que é ACID?", a: "Propriedades de transação segura.", cat: "backend", nivel: "pleno" },
    { q: "O que é indexação em DB?", a: "Estrutura para busca rápida.", cat: "backend", nivel: "pleno" },
    { q: "O que é load balancer?", a: "Distribui tráfego entre servidores.", cat: "backend", nivel: "pleno" },
    { q: "Diferença entre monolith e microservices?", a: "Single app vs serviços desacoplados.", cat: "backend", nivel: "pleno" },
    { q: "O que é Redis?", a: "Armazenamento em cache na memória.", cat: "backend", nivel: "pleno" },
    { q: "O que é orm?", a: "Mapper que transforma objeto em SQL.", cat: "backend", nivel: "pleno" },
    { q: "O que é SQL Injection?", a: "Falha de segurança com queries injetadas.", cat: "backend", nivel: "pleno" },
    { q: "O que é OAuth2?", a: "Protocolo de autorização padrão.", cat: "backend", nivel: "pleno" },
    { q: "O que são workers?", a: "Processos de fundo para tarefas pesadas.", cat: "backend", nivel: "pleno" },
    { q: "O que é CI/CD?", a: "Integração e entrega contínua.", cat: "backend", nivel: "pleno" },
    { q: "O que é hashing?", a: "Transformar dado em hash irreversível.", cat: "backend", nivel: "pleno" },
    { q: "O que é SALT?", a: "Valor aleatório para fortalecer o hash.", cat: "backend", nivel: "pleno" },
    { q: "O que é websockets?", a: "Conexão bidirecional em tempo real.", cat: "backend", nivel: "pleno" },
    { q: "O que é mensageria (RabbitMQ)?", a: "Fila de mensagens entre serviços.", cat: "backend", nivel: "pleno" },
    { q: "O que é rate limiting?", a: "Limitar requisições por usuário.", cat: "backend", nivel: "pleno" },
    { q: "O que é serverless?", a: "Execução sem gerenciar infra.", cat: "backend", nivel: "pleno" },
    { q: "O que é grpc?", a: "Protocolo RPC de alto desempenho.", cat: "backend", nivel: "pleno" },
    { q: "O que é um dead-letter queue?", a: "Fila para mensagens que falharam.", cat: "backend", nivel: "pleno" },
    { q: "O que é o garbage collector?", a: "Limpeza automática de memória.", cat: "backend", nivel: "pleno" },
    { q: "O que é sharding?", a: "Dividir banco em múltiplos servidores.", cat: "backend", nivel: "pleno" },
    { q: "O que é idempotência?", a: "Repetir requisição sem mudar efeito.", cat: "backend", nivel: "pleno" },
    { q: "O que é um cluster?", a: "Grupo de servidores funcionando como um.", cat: "backend", nivel: "pleno" },
    { q: "O que é refatoração?", a: "Melhorar código sem mudar comportamento.", cat: "backend", nivel: "pleno" },
    { q: "O que é um mock em teste?", a: "Simulação de dependência externa.", cat: "backend", nivel: "pleno" },
    { q: "O que é grpc?", a: "Protocolo eficiente entre microsserviços.", cat: "backend", nivel: "pleno" },
    { q: "O que é tracing?", a: "Monitorar requisição em sistemas distribuídos.", cat: "backend", nivel: "pleno" },
    { q: "O que é grafana?", a: "Ferramenta de monitoramento e visualização.", cat: "backend", nivel: "pleno" },
    { q: "O que é orquestração?", a: "Gerenciar containers (ex: Kubernetes).", cat: "backend", nivel: "pleno" }
];